### ISSUE TITLE
Color theme in full UI

### ISSUE THREAD

**Issue by XOSplicer** [veggiemonk/theme-solarized-light-fjs#1]
Hi, I really love your theme and been using it for a long time now. It has great readability and works for a variety of languages.

However only the editor section is styled.
Maybe this is intended.
I personally like to have the full UI styled, not only the editor.
Therefore I am using a style customization in my settings.json file (source and screenshot below).

@veggiemonk Do you think integrating this could enhance the theme?

```
"workbench.colorCustomizations": {
        "[Solarized-light-fjs]": {
            "peekViewResult.background": "#EEE8D5",
            "peekViewEditor.background": "#FFFBF2",
            "peekViewTitle.background": "#EEE8D5",
            "peekView.border": "#B58900",
            "peekViewEditor.matchHighlightBackground": "#7744AA40",
            "titleBar.activeBackground": "#EEE8D5",
            "editorGroup.border": "#DDD6C1",
            "editorGroup.dropBackground": "#DDD6C1AA",
            "editorGroupHeader.tabsBackground": "#D9D2C2",
            "tab.border": "#DDD6C1",
            "tab.activeBackground": "#FDF6E3",
            "tab.inactiveForeground": "#586E75",
            "tab.inactiveBackground": "#D3CBB7",
            "activityBar.background": "#DDD6C1",
            "activityBar.foreground": "#584c27",
            "activityBar.dropBackground": "#EEE8D5",
            "activityBarBadge.background": "#B58900",
            "panel.border": "#DDD6C1",
            "sideBar.background": "#EEE8D5",
            "sideBarTitle.foreground": "#586E75",
            "statusBar.foreground": "#586E75",
            "statusBar.background": "#EEE8D5",
            "statusBar.debuggingBackground": "#EEE8D5",
            "statusBar.noFolderBackground": "#EEE8D5",
            "statusBarItem.prominentBackground": "#DDD6C1",
            "statusBarItem.prominentHoverBackground": "#DDD6C199",
            "debugToolBar.background": "#DDD6C1",
            "debugExceptionWidget.background": "#DDD6C1",
            "debugExceptionWidget.border": "#AB395B",
            "pickerGroup.border": "#2AA19899",
            "pickerGroup.foreground": "#2AA19899",
            "extensionButton.prominentBackground": "#b58900",
            "extensionButton.prominentHoverBackground": "#584c27aa",
            // Colors sourced from the official palette http://ethanschoonover.com/solarized
            "terminal.ansiBlack": "#073642",
            "terminal.ansiRed": "#dc322f",
            "terminal.ansiGreen": "#859900",
            "terminal.ansiYellow": "#b58900",
            "terminal.ansiBlue": "#268bd2",
            "terminal.ansiMagenta": "#d33682",
            "terminal.ansiCyan": "#2aa198",
            "terminal.ansiWhite": "#eee8d5",
            "terminal.ansiBrightBlack": "#586e75",
            "terminal.ansiBrightRed": "#cb4b16",
            "terminal.ansiBrightGreen": "#586e75",
            "terminal.ansiBrightYellow": "#657b83",
            "terminal.ansiBrightBlue": "#839496",
            "terminal.ansiBrightMagenta": "#6c71c4",
            "terminal.ansiBrightCyan": "#93a1a1",
            "terminal.ansiBrightWhite": "#eee8d5"
        }
    }
```
![image](https://user-images.githubusercontent.com/16841603/42439016-fcc199f6-8361-11e8-81a0-e28e9a5e6883.png)

**Comment by veggiemonk** [comment]
Hi @XOSplicer,

Sure! That would be a great addition. 
If you'd like, you can submit a PR or I can integrate the change myself 😄 

Good suggestion 👍

**Comment by XOSplicer** [comment]
Thanks for the fast reply.

Check out this modified theme file which was generated by code automatically:
https://github.com/XOSplicer/theme-solarized-light-fjs-improved/blob/master/themes/Solarized-light-fjs-improved-color-theme.json
This is an easy start for a PR.
I sure can fork your theme and apply the changes.

I don't know if it would be better to do a PR and release a **new version of this theme**
or to release a **new theme** with the fixed background, since this is kind of "breaking change" in the visual sense.
Another alternative is to ship the new alternative **alongside with the old** by adding a second `contributes` entry into the `package.json`.
What is your oppinion on this?

**Comment by veggiemonk** [comment]
As I use this theme daily, I found that the full UI theme is much easier on the eyes. 

If you want to create a new theme, by all means, go ahead. 
This was originally meant for my personal use, I didn't know people were using it 😅 
 
I'm glad you did use it! 

So I created a PR : https://github.com/veggiemonk/theme-solarized-light-fjs/pull/2

Let me know what you think

**Comment by XOSplicer** [comment]
Looks great to me.

I tested it on my system (Windows 10, VS Code 1.25.0) and it works as expected.

I noticed you renamed the theme and package to `solarized-light-functional` and increased the major version. I think VS Code therefore sees it as completely new extension.

If you want, you can merge publish it.
I don't see a need to release the theme myself if you integrate the changes 😄

**Comment by veggiemonk** [comment]
You were right, creating a new extension is better: https://github.com/veggiemonk/theme-solarized-light-functional
